version: '3.1'

services:

  mongo:
    image: mongo
    container_name: ms-order
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_INITDB_DATABASE: ms-order
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network

networks:
  my-network:
  rabbitmq-network:
    driver: bridge