version: '3.1'

services:

  mongo2:
    image: mongo
    container_name: ms-payment
    restart: always
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_INITDB_DATABASE: ms-order
